import {
  DEV_BACKEND_URL_API_KEY,
  DEV_BACKEND_URL_AUTH_DOMAIN,
  DEV_BACKEND_URL_PROJECT_ID,
  DEV_BACKEND_URL_STORAGE_BUCKET,
  DEV_BACKEND_URL_MESSAGING_SENDER_ID,
  DEV_BACKEND_URL_APP_ID,
  DEV_BACKEND_URL_MEASUREMENT_ID,
} from '@env'

const devEnvironmentVariables = {
  DEV_BACKEND_URL_API_KEY,
  DEV_BACKEND_URL_AUTH_DOMAIN,
  DEV_BACKEND_URL_PROJECT_ID,
  DEV_BACKEND_URL_STORAGE_BUCKET,
  DEV_BACKEND_URL_MESSAGING_SENDER_ID,
  DEV_BACKEND_URL_APP_ID,
  DEV_BACKEND_URL_MEASUREMENT_ID,
}

const prodEnvironmentVariables = {
  DEV_BACKEND_URL_API_KEY,
  DEV_BACKEND_URL_AUTH_DOMAIN,
  DEV_BACKEND_URL_PROJECT_ID,
  DEV_BACKEND_URL_STORAGE_BUCKET,
  DEV_BACKEND_URL_MESSAGING_SENDER_ID,
  DEV_BACKEND_URL_APP_ID,
  DEV_BACKEND_URL_MEASUREMENT_ID,
}

export default devEnvironmentVariables;
